#!/bin/bash

TEST=$(dirname $0)

echo -n "Running $TEST: "

if gs --version | grep -q '^7\.'; then
  echo "SKIPPED GS too old"
  exit 0
fi

OUT=$(cd build/resource/Resource && gs -sNOSAFER -dNOPAUSE -dBATCH -sDEVICE=nullpage -P ../../../$TEST/test.ps 2>&1)

if [ $? -eq 0 ] && echo "$OUT" | grep -qFx 'PASS'; then
  echo "PASS"
  exit 0
else
  echo "FAIL"
  echo
  echo "$OUT"
  echo
  exit 1
fi

