#!/bin/bash

TEST=$(dirname "$0")

echo -n "Running $TEST: "

if gs --version | grep -q '^7\.'; then
  echo "SKIPPED GS too old"
  exit 0
fi

if gs -dBATCH -dNODISPLAY -dQUIET -c '401 string { dup } forall count =' | grep -qFx 800; then
  STRING_CONTINUE_BUG=-dSTRING_CONTINUE_BUG
fi

if OUT=$(cd build/resource/Resource && gs -sNOSAFER -dNOPAUSE -dBATCH -sDEVICE=nullpage $STRING_CONTINUE_BUG -P ../../../"$TEST"/test.ps 2>&1); then
  if echo "$OUT" | grep -qFx 'PASS'; then
    echo "PASS"
    exit 0
  fi
fi

echo "FAIL"
echo
echo "$OUT"
echo
exit 1
