#!/bin/bash

# Barcode Writer in Pure PostScript
# https://bwipp.terryburton.co.uk
#
# Copyright (c) 2004-2026 Terry Burton

set -e
set -u
set -o pipefail

TESTDIR=$(dirname "$0")

"$TESTDIR"/test_requires/run
"$TESTDIR"/ps_tests/run
"$TESTDIR"/test_monolithic/run
"$TESTDIR"/test_monolithic_package/run
"$TESTDIR"/test_resource/run
"$TESTDIR"/test_packaged_resource/run

echo "All tests passed."
