#!/bin/bash

set -e

TESTDIR=$(dirname $0)

$TESTDIR/test_monolithic/run
$TESTDIR/test_monolithic_package/run
$TESTDIR/test_resource/run
$TESTDIR/test_packaged_resource/run
$TESTDIR/ps_tests/run

echo "All tests passed."

