#!/bin/bash

# Barcode Writer in Pure PostScript
# https://bwipp.terryburton.co.uk
#
# Copyright (c) 2004-2024 Terry Burton

set -e
set -u
set -o pipefail

TEST=$(dirname "$0")

echo -n "Running $TEST: "

if gs -dNOPAUSE -dSAFER -dQUIET -dBATCH -sDEVICE=nullpage build/monolithic_package/barcode_with_sample.ps; then
	echo "PASS"
	exit 0
else
	echo "FAIL"
	exit 1
fi
