#!/bin/bash

TEST=$(dirname $0)

echo -n "Running $TEST: "

gs -dNOPAUSE -dSAFER -dQUIET -dBATCH -sDEVICE=nullpage build/monolithic_package/barcode_with_sample.ps

if [ $? -eq 0 ]; then
  echo "PASS"
  exit 0
else
  echo "FAIL"
  exit 1
fi

