#!/bin/bash

TEST=$(dirname "$0")

echo -n "Running $TEST: "

if gs -dNOPAUSE -dSAFER -dQUIET -dBATCH -sDEVICE=nullpage build/monolithic/barcode_with_sample.ps; then
	echo "PASS"
	exit 0
else
	echo "FAIL"
	exit 1
fi
